create TABLE booking (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   description VARCHAR(255),
   time_from TIMESTAMP WITHOUT TIME ZONE,
   time_to TIMESTAMP WITHOUT TIME ZONE,
   owner_id BIGINT,
   meet_room_id BIGINT,
   CONSTRAINT pk_booking PRIMARY KEY (id)
);

create TABLE booking_employee (
  booking_id BIGINT NOT NULL,
   employee_id BIGINT NOT NULL,
   CONSTRAINT pk_booking_employee PRIMARY KEY (booking_id, employee_id)
);

create TABLE employee (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255),
   password VARCHAR(255),
   CONSTRAINT pk_employee PRIMARY KEY (id)
);

create TABLE meet_room (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_meetroom PRIMARY KEY (id)
);

create TABLE role (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   CONSTRAINT pk_role PRIMARY KEY (id)
);

create TABLE employee_role (
  role_id BIGINT NOT NULL,
   employee_id BIGINT NOT NULL,
   CONSTRAINT pk_employee_role PRIMARY KEY (role_id, employee_id)
);

alter table booking add CONSTRAINT FK_BOOKING_ON_MEET_ROOM FOREIGN KEY (meet_room_id) REFERENCES meet_room (id);

alter table booking add CONSTRAINT FK_BOOKING_ON_OWNER FOREIGN KEY (owner_id) REFERENCES employee (id);

alter table booking_employee add CONSTRAINT fk_booemp_on_booking FOREIGN KEY (booking_id) REFERENCES booking (id);

alter table booking_employee add CONSTRAINT fk_booemp_on_employee FOREIGN KEY (employee_id) REFERENCES employee (id);

alter table employee_role add CONSTRAINT fk_employee_role_on_employee FOREIGN KEY (employee_id) REFERENCES employee (id);

alter table employee_role add CONSTRAINT fk_employee_role_on_role FOREIGN KEY (role_id) REFERENCES role (id);